// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_yiPyqekgwOLV4CqWAM4YtA-zFYqEI8Y',
    appId: '1:232278829300:web:85451a4968ba36ee4356a1',
    messagingSenderId: '232278829300',
    projectId: 'blog-app-d70a4',
    authDomain: 'blog-app-d70a4.firebaseapp.com',
    storageBucket: 'blog-app-d70a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9o5rAIHrcgW1GR30WFrqJ5Y6tVNYoJI',
    appId: '1:232278829300:android:2e6967bdd54fc0b94356a1',
    messagingSenderId: '232278829300',
    projectId: 'blog-app-d70a4',
    storageBucket: 'blog-app-d70a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiAzV9zjPnn2qGe3Y8N67aXrbuO_tHgk',
    appId: '1:232278829300:ios:c19c50b162b488274356a1',
    messagingSenderId: '232278829300',
    projectId: 'blog-app-d70a4',
    storageBucket: 'blog-app-d70a4.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );
}
